import {Router} from 'express';import {q,one,transaction} from './db.js';import {z,str,id,ok,wrap,fail,roles,versionSchema,money,checkVersion,audit,notify,state} from './common.js';
export const adminRouter=Router();
export const publicServices=wrap(async(req,res)=>ok(res,await q('SELECT * FROM dbo.DichVu WHERE isActive=1 ORDER BY id')));
const serviceSchema=z.strictObject({name:str(2,150),groupCode:z.enum(['DienLanh','DienNuoc','DienGiaDung','VeSinh']),description:str(5,1500),inspectionFee:money,laborFee:money,commissionRatePercent:z.string().regex(/^\d{1,3}(\.\d{1,2})?$/).refine(s=>Number(s)<=100),isActive:z.boolean()});
adminRouter.get('/admin/services',roles('ADMIN'),wrap(async(req,res)=>ok(res,await q('SELECT * FROM dbo.DichVu ORDER BY id'))));
adminRouter.post('/services',roles('ADMIN'),wrap(async(req,res)=>{const b=serviceSchema.parse(req.body);ok(res,await transaction(req.user,async t=>{const s=await one('INSERT dbo.DichVu(name,groupCode,description,inspectionFee,laborFee,commissionRatePercent,isActive) OUTPUT INSERTED.* VALUES(@name,@groupCode,@description,CAST(@inspectionFee AS decimal(18,2)),CAST(@laborFee AS decimal(18,2)),CAST(@commissionRatePercent AS decimal(5,2)),@isActive)',b,t);await audit(t,req.user,'CreateService','DichVu',s.id);return s;}),201);}));
adminRouter.patch('/services/:id',roles('ADMIN'),wrap(async(req,res)=>{const sid=id(req.params.id),b=serviceSchema.extend({expectedVersion:versionSchema}).parse(req.body);ok(res,await transaction(req.user,async t=>{const s=await one('SELECT * FROM dbo.DichVu WHERE id=@id',{id:sid},t);checkVersion(s,b.expectedVersion);await q('UPDATE dbo.DichVu SET name=@name,groupCode=@groupCode,description=@description,inspectionFee=CAST(@inspectionFee AS decimal(18,2)),laborFee=CAST(@laborFee AS decimal(18,2)),commissionRatePercent=CAST(@commissionRatePercent AS decimal(5,2)),isActive=@isActive WHERE id=@id',{...b,id:sid},t);await audit(t,req.user,'UpdateService','DichVu',sid);return one('SELECT * FROM dbo.DichVu WHERE id=@id',{id:sid},t);}));}));
adminRouter.get('/app-config',wrap(async(req,res)=>{const values=Object.fromEntries((await q('SELECT [key],value FROM dbo.CauHinh')).map(r=>[r.key,r.value]));ok(res,{...values,signatureRequired:values.signatureRequired==='true',supportedPaymentMethods:['COD'],maxOrderImages:5,maxImageBytes:5242880,enabledFeatures:{wallet:true,support:true,notifications:true,location:true,onlinePayment:false}});}));
adminRouter.get('/settings',roles('ADMIN'),wrap(async(req,res)=>ok(res,await q('SELECT * FROM dbo.CauHinh ORDER BY [key]'))));
adminRouter.patch('/settings/:key',roles('ADMIN'),wrap(async(req,res)=>{const key=z.enum(['minimumWallet','assignmentMinutes','cancellationFee','signatureRequired']).parse(req.params.key),b=z.strictObject({value:str(1,100),expectedVersion:versionSchema}).parse(req.body);if(key==='signatureRequired'){if(!['true','false'].includes(b.value))fail(422,'INVALID_SETTING','Giá trị phải là true hoặc false.');}else{if(!/^\d+$/.test(b.value))fail(422,'INVALID_SETTING','Giá trị phải là số nguyên không âm.');const v=Number(b.value);if(v>10000000||(key==='assignmentMinutes'&&(v<1||v>60)))fail(422,'INVALID_SETTING','Giá trị ngoài giới hạn.');}
 ok(res,await transaction(req.user,async t=>{const s=await one('SELECT * FROM dbo.CauHinh WHERE [key]=@key',{key},t);checkVersion(s,b.expectedVersion);await q('UPDATE dbo.CauHinh SET value=@value WHERE [key]=@key',{key,value:b.value},t);await audit(t,req.user,'UpdateSetting','CauHinh',null,key);return one('SELECT * FROM dbo.CauHinh WHERE [key]=@key',{key},t);}));}));
adminRouter.get('/audit-logs',roles('ADMIN'),wrap(async(req,res)=>ok(res,await q('SELECT TOP 200 a.*,n.fullName actorName FROM dbo.NhatKy a LEFT JOIN dbo.NguoiDung n ON n.id=a.actorId ORDER BY a.id DESC'))));
adminRouter.get('/notifications',wrap(async(req,res)=>ok(res,await q('SELECT TOP 100 * FROM dbo.ThongBao WHERE userId=@id ORDER BY id DESC',{id:req.user.id}))));
adminRouter.patch('/notifications/:id/read',wrap(async(req,res)=>{const nid=id(req.params.id);const n=await transaction(req.user,async t=>{const n=await one('SELECT * FROM dbo.ThongBao WHERE id=@id AND userId=@uid',{id:nid,uid:req.user.id},t);if(!n)fail(404,'NOT_FOUND','Không tìm thấy thông báo.');await q('UPDATE dbo.ThongBao SET readAt=COALESCE(readAt,SYSUTCDATETIME()) WHERE id=@id',{id:nid},t);return one('SELECT * FROM dbo.ThongBao WHERE id=@id',{id:nid},t);});ok(res,n);}));
adminRouter.post('/technician-applications',roles('KH'),wrap(async(req,res)=>{const b=z.strictObject({skillGroup:z.enum(['DienLanh','DienNuoc','DienGiaDung','VeSinh']),serviceArea:str(2,120),experience:str(10,2000)}).parse(req.body);ok(res,await transaction(req.user,t=>one('INSERT dbo.HoSoKTV(userId,skillGroup,serviceArea,experience) OUTPUT INSERTED.* VALUES(@uid,@skillGroup,@serviceArea,@experience)',{uid:req.user.id,...b},t)),201);}));
adminRouter.get('/technician-applications/me',roles('KH','KTV'),wrap(async(req,res)=>ok(res,await q('SELECT * FROM dbo.HoSoKTV WHERE userId=@id ORDER BY id DESC',{id:req.user.id}))));
adminRouter.get('/technician-applications',roles('ADMIN'),wrap(async(req,res)=>ok(res,await q('SELECT h.*,n.fullName,n.phone FROM dbo.HoSoKTV h JOIN dbo.NguoiDung n ON n.id=h.userId ORDER BY h.id DESC'))));
adminRouter.post('/technician-applications/:id/decision',roles('ADMIN'),wrap(async(req,res)=>{const hid=id(req.params.id),b=z.strictObject({decision:z.enum(['Approved','Rejected']),reason:str(1,1000).optional(),expectedVersion:versionSchema}).parse(req.body);if(b.decision==='Rejected'&&!b.reason)fail(422,'REASON_REQUIRED','Cần lý do từ chối.');ok(res,await transaction(req.user,async t=>{const h=await one('SELECT * FROM dbo.HoSoKTV WHERE id=@id',{id:hid},t);checkVersion(h,b.expectedVersion);state(h,'Pending');if(b.decision==='Approved'){const u=await one('SELECT role FROM dbo.NguoiDung WHERE id=@id',{id:h.userId},t);if(u.role!=='KH')fail(409,'ROLE_CHANGED','Vai trò người nộp đã thay đổi.');if(await one("SELECT id FROM dbo.DonHang WHERE customerId=@id AND status NOT IN('HoanThanh','Huy')",{id:h.userId},t))fail(409,'OPEN_CUSTOMER_ORDER','Người nộp còn đơn khách hàng chưa hoàn tất.');await q("UPDATE dbo.NguoiDung SET role='KTV',tokenVersion=tokenVersion+1 WHERE id=@id",{id:h.userId},t);await q('INSERT dbo.KyThuatVien(id,skillGroup,serviceArea) VALUES(@id,@skill,@area)',{id:h.userId,skill:h.skillGroup,area:h.serviceArea},t);}await q('UPDATE dbo.HoSoKTV SET status=@decision,reason=@reason,decidedBy=@uid WHERE id=@id',{id:hid,decision:b.decision,reason:b.reason,uid:req.user.id},t);await audit(t,req.user,'DecideApplication','HoSoKTV',hid,b.decision);return one('SELECT * FROM dbo.HoSoKTV WHERE id=@id',{id:hid},t);}));}));
function period(req){const schema=z.iso.datetime({offset:true});const from=req.query.from?new Date(schema.parse(req.query.from)):new Date('2020-01-01T00:00:00Z');const to=req.query.to?new Date(schema.parse(req.query.to)):new Date(Date.now()+86400000);if(from>=to)fail(422,'INVALID_PERIOD','Ngày kết thúc phải sau ngày bắt đầu.');return {from,to};}
adminRouter.get('/reports/summary',roles('GD','KT','CSKH','ADMIN','DPV'),wrap(async(req,res)=>{const params=period(req);const orders=await one("SELECT COUNT(*) totalOrders,COALESCE(SUM(CASE WHEN status='HoanThanh' THEN 1 ELSE 0 END),0) completedOrders,COALESCE(SUM(CASE WHEN status='Huy' THEN 1 ELSE 0 END),0) cancelledOrders FROM dbo.DonHang WHERE createdAt>=@from AND createdAt<@to",params);const money=await one('SELECT COALESCE(SUM(amount),0) gmv,COUNT(*) paidOrders FROM dbo.ThanhToan WHERE paidAt>=@from AND paidAt<@to',params);const commission=await one("SELECT COALESCE(SUM(commissionAmount),0) commissionRevenue FROM dbo.DoiSoat WHERE status='Confirmed' AND confirmedAt>=@from AND confirmedAt<@to",params);const quality=await one('SELECT AVG(CAST(rating AS decimal(5,2))) averageRating,COUNT(*) reviews FROM dbo.DanhGia WHERE createdAt>=@from AND createdAt<@to',params);const trend=await q('SELECT CONVERT(varchar(10),DATEADD(hour,7,paidAt),23) day,SUM(amount) amount,COUNT(*) orders FROM dbo.ThanhToan WHERE paidAt>=@from AND paidAt<@to GROUP BY CONVERT(varchar(10),DATEADD(hour,7,paidAt),23) ORDER BY day',params);ok(res,{...orders,...money,...commission,...quality,trend});}));
adminRouter.get('/reports/technicians',roles('GD','KT','DPV'),wrap(async(req,res)=>ok(res,await q("SELECT k.id,n.fullName,k.skillGroup,k.availability,(SELECT COUNT(*) FROM dbo.ThanhToan p WHERE p.receivedBy=k.id) completedOrders,(SELECT AVG(CAST(rating AS decimal(5,2))) FROM dbo.DanhGia d WHERE d.technicianId=k.id) averageRating FROM dbo.KyThuatVien k JOIN dbo.NguoiDung n ON n.id=k.id"))));
adminRouter.get('/reports/finance',roles('GD','KT'),wrap(async(req,res)=>ok(res,await q('SELECT p.id,p.orderId,p.amount,p.paidAt,n.fullName technicianName,s.commissionAmount,s.status settlementStatus FROM dbo.ThanhToan p JOIN dbo.NguoiDung n ON n.id=p.receivedBy JOIN dbo.DoiSoat s ON s.paymentId=p.id WHERE p.paidAt>=@from AND p.paidAt<@to ORDER BY p.id DESC',period(req)))));
adminRouter.get('/reports/finance.csv',roles('GD','KT'),wrap(async(req,res)=>{const rows=await q('SELECT p.orderId,p.amount,p.paidAt,s.commissionAmount,s.status FROM dbo.ThanhToan p JOIN dbo.DoiSoat s ON s.paymentId=p.id WHERE p.paidAt>=@from AND p.paidAt<@to ORDER BY p.id',period(req));const lines=['orderId,amount,paidAt,commissionAmount,status',...rows.map(r=>[r.orderId,r.amount,new Date(r.paidAt).toISOString(),r.commissionAmount,r.status].join(','))];res.attachment('HomeFix_Finance.csv').type('text/csv').send('\ufeff'+lines.join('\r\n'));}));
