import { Router } from 'express'; import { q, one, transaction, sql } from './db.js';
import { z, str, id, ok, wrap, fail, roles, versionSchema, money, checkVersion, state, getOrder, notify, audit, idempotent } from './common.js';
export const financeRouter = Router();
financeRouter.get('/orders/:id/invoice', roles('KH', 'KTV', 'KT'), wrap(async (req, res) => { const oid = id(req.params.id); await getOrder(oid, req.user); const a = await one("SELECT * FROM dbo.PhieuNghiemThu WHERE orderId=@id AND status='Approved'", { id: oid }); if (!a) fail(409, 'INVOICE_NOT_READY', 'Khách chưa xác nhận nghiệm thu.'); const receipt = await one('SELECT * FROM dbo.ThanhToan WHERE orderId=@id', { id: oid }); ok(res, { ...a, paymentStatus: receipt ? 'Paid' : 'Unpaid', receipt: receipt ?? null }); }));
financeRouter.get('/orders/:id/payments', roles('KH', 'KTV', 'KT'), wrap(async (req, res) => { const oid = id(req.params.id); await getOrder(oid, req.user); ok(res, await q('SELECT * FROM dbo.ThanhToan WHERE orderId=@id', { id: oid })); }));
financeRouter.post('/orders/:id/payments/cod', roles('KTV'), wrap(async (req, res) => {
  const oid = id(req.params.id), b = z.strictObject({ expectedVersion: versionSchema }).parse(req.body);
  const result = await transaction(req.user, async t => {
    const o = await getOrder(oid, req.user, t); const a = await one("SELECT * FROM dbo.PhieuNghiemThu WHERE orderId=@id AND status='Approved'", { id: oid }, t);
    if (!a) { state(o, 'HoanThanh'); fail(409, 'ACCEPTANCE_REQUIRED', 'Chưa nghiệm thu.'); } if (a.technicianId !== req.user.id) fail(404, 'NOT_FOUND', 'Bạn không phải thợ thực hiện.');
    return idempotent(t, req, b, async () => {
      checkVersion(o, b.expectedVersion); state(o, 'HoanThanh'); if (o.paymentMethod !== 'COD') fail(409, 'PAYMENT_METHOD_MISMATCH', 'Khách đang chọn chuyển khoản. Không được thu thêm tiền mặt.'); if (await one('SELECT id FROM dbo.ThanhToan WHERE orderId=@id', { id: oid }, t)) fail(409, 'PAYMENT_ALREADY_PAID', 'Đơn đã được ghi nhận thu tiền.');
      const p = await one("INSERT dbo.ThanhToan(orderId,acceptanceId,amount,receivedBy) OUTPUT INSERTED.* SELECT orderId,id,total,technicianId FROM dbo.PhieuNghiemThu WHERE id=@aid", { aid: a.id }, t);
      await q('INSERT dbo.DoiSoat(orderId,technicianId,paymentId,laborFee,commissionRatePercent) SELECT @oid,@kid,@pid,laborFee,commissionRatePercent FROM dbo.BaoGiaSoBo WHERE orderId=@oid', { oid, kid: req.user.id, pid: p.id }, t);
      await q('UPDATE dbo.DonHang SET updatedAt=SYSUTCDATETIME() WHERE id=@id', { id: oid }, t); await audit(t, req.user, 'ReceiveCOD', 'ThanhToan', p.id); await notify(t, o.customerId, oid, 'Đã ghi nhận thanh toán COD', 'Cảm ơn bạn. Bạn có thể đánh giá dịch vụ.'); return p;
    });
  }); ok(res, result.data, result.replay ? 200 : 201);
}));
financeRouter.get('/settlements', roles('KT'), wrap(async (req, res) => ok(res, await q('SELECT s.*,n.fullName technicianName,p.amount,p.paidAt,p.method,p.amount-s.commissionAmount technicianCredit,a.materialTotal FROM dbo.DoiSoat s JOIN dbo.NguoiDung n ON n.id=s.technicianId JOIN dbo.ThanhToan p ON p.id=s.paymentId JOIN dbo.PhieuNghiemThu a ON a.id=p.acceptanceId ORDER BY s.id DESC'))));
financeRouter.post('/settlements/:id/confirm', roles('KT'), wrap(async (req, res) => {
  const sid = id(req.params.id), b = z.strictObject({ expectedVersion: versionSchema }).parse(req.body);
  const r = await transaction(req.user, t => idempotent(t, req, b, async () => { const r = new sql.Request(t); r.input('SettlementId', sql.Int, sid).input('ActorId', sql.Int, req.user.id).input('ExpectedVersion', sql.Binary(8), Buffer.from(b.expectedVersion, 'base64')); await r.execute('dbo.sp_DoiSoatCOD'); return one('SELECT * FROM dbo.DoiSoat WHERE id=@id', { id: sid }, t); })); ok(res, r.data);
}));
financeRouter.get('/technicians/me/wallet', roles('KTV'), wrap(async (req, res) => { const k = await one('SELECT balance,version FROM dbo.KyThuatVien WHERE id=@id', { id: req.user.id }); ok(res, { ...k, transactions: await q('SELECT * FROM dbo.GiaoDichVi WHERE technicianId=@id ORDER BY id DESC', { id: req.user.id }) }); }));
financeRouter.get('/technicians/me/income', roles('KTV'), wrap(async (req, res) => ok(res, await one('SELECT COALESCE(SUM(a.inspectionFee+a.laborFee-s.commissionAmount),0) income,COALESCE(SUM(a.materialTotal),0) materialReimbursement,COUNT(*) completedOrders FROM dbo.ThanhToan p JOIN dbo.PhieuNghiemThu a ON a.id=p.acceptanceId JOIN dbo.DoiSoat s ON s.paymentId=p.id WHERE s.technicianId=@id', { id: req.user.id }))));
financeRouter.get('/wallet-requests', roles('KTV', 'KT'), wrap(async (req, res) => ok(res, await q(`SELECT w.*,n.fullName technicianName FROM dbo.YeuCauVi w JOIN dbo.NguoiDung n ON n.id=w.technicianId ${req.user.role === 'KTV' ? 'WHERE technicianId=@id' : ''} ORDER BY w.id DESC`, { id: req.user.id }))));
financeRouter.post('/wallet-requests', roles('KTV'), wrap(async (req, res) => {
  const b = z.strictObject({ type: z.enum(['Deposit', 'Withdrawal']), amount: money.refine(s => Number(s) > 0), note: str(5, 1000), proofId: z.number().int().positive().optional() }).parse(req.body);
  const r = await transaction(req.user, t => idempotent(t, req, b, async () => { if (b.type === 'Deposit' && !b.proofId) fail(422, 'PROOF_REQUIRED', 'Yêu cầu nạp cần ảnh chứng từ demo.'); if (b.proofId && !await one("SELECT id FROM dbo.TepDinhKem WHERE id=@id AND ownerId=@uid AND purpose='WalletProof'", { id: b.proofId, uid: req.user.id }, t)) fail(404, 'ATTACHMENT_NOT_FOUND', 'Chứng từ không hợp lệ.'); return one('INSERT dbo.YeuCauVi(technicianId,type,amount,note,proofId) OUTPUT INSERTED.* VALUES(@uid,@type,CAST(@amount AS decimal(18,2)),@note,@proofId)', { uid: req.user.id, proofId: null, ...b }, t); })); ok(res, r.data, r.replay ? 200 : 201);
}));
financeRouter.post('/wallet-requests/:id/decision', roles('KT'), wrap(async (req, res) => {
  const wid = id(req.params.id), b = z.strictObject({ decision: z.enum(['Approved', 'Rejected']), reason: str(1, 1000).optional(), expectedVersion: versionSchema }).parse(req.body); if (b.decision === 'Rejected' && !b.reason) fail(422, 'REASON_REQUIRED', 'Cần lý do từ chối.');
  const r = await transaction(req.user, t => idempotent(t, req, b, async () => {
    const w = await one('SELECT * FROM dbo.YeuCauVi WHERE id=@id', { id: wid }, t); checkVersion(w, b.expectedVersion); state(w, 'Pending'); if (b.decision === 'Approved') {
      if (w.type === 'Withdrawal') { const k = await one('SELECT balance FROM dbo.KyThuatVien WHERE id=@id', { id: w.technicianId }, t); if (Number(k.balance) < Number(w.amount)) fail(409, 'INSUFFICIENT_BALANCE', 'Ví không đủ để duyệt rút.'); if (await one('SELECT id FROM dbo.LenhDieuPhoi WHERE technicianId=@id AND isActive=1', { id: w.technicianId }, t)) fail(409, 'ACTIVE_ASSIGNMENT', 'Chưa duyệt rút khi kỹ thuật viên đang giữ ca.'); }
      await q('INSERT dbo.GiaoDichVi(technicianId,type,amount,referenceType,referenceId,actorId,note) SELECT technicianId,type,CASE WHEN type=\'Withdrawal\' THEN -amount ELSE amount END,\'WalletRequest\',id,@uid,note FROM dbo.YeuCauVi WHERE id=@id', { id: wid, uid: req.user.id }, t);
    } await q('UPDATE dbo.YeuCauVi SET status=@decision,reason=@reason,decidedBy=@uid,decidedAt=SYSUTCDATETIME() WHERE id=@id', { id: wid, decision: b.decision, reason: b.reason, uid: req.user.id }, t); await audit(t, req.user, 'DecideWallet', 'YeuCauVi', wid, b.decision); await notify(t, w.technicianId, null, 'Yêu cầu ví đã được xử lý', b.decision === 'Approved' ? 'Đã duyệt và ghi sổ.' : b.reason); return one('SELECT * FROM dbo.YeuCauVi WHERE id=@id', { id: wid }, t);
  })); ok(res, r.data);
}));
financeRouter.post('/wallet-requests/:id/cancel', roles('KTV'), wrap(async (req, res) => { const wid = id(req.params.id), b = z.strictObject({ expectedVersion: versionSchema }).parse(req.body); const w = await transaction(req.user, async t => { const w = await one('SELECT * FROM dbo.YeuCauVi WHERE id=@id AND technicianId=@uid', { id: wid, uid: req.user.id }, t); checkVersion(w, b.expectedVersion); state(w, 'Pending'); await q("UPDATE dbo.YeuCauVi SET status='Cancelled' WHERE id=@id", { id: wid }, t); return one('SELECT * FROM dbo.YeuCauVi WHERE id=@id', { id: wid }, t); }); ok(res, w); }));
