import {PasswordChange} from './auth-forms';
import React,{useEffect,useRef,useState} from 'react';import {Link,useNavigate,useParams} from 'react-router-dom';import {ArrowRight,Plus,Snowflake,Refrigerator,WashingMachine,PlugZap,Droplets,Sparkles,ShieldCheck,Clock,Star,Wallet,MapPin,CalendarDays,Bell,Check,RefreshCw} from 'lucide-react';
import {api,upload,uuid} from './api';import {useApp,useData,useAction,PageHead,Card,Field,ErrorBox,Loading,Empty,Submit,OrderCard,Badge,money,date,groups,roleNames,labels} from './shared';
const icons=[Snowflake,Sparkles,Refrigerator,WashingMachine,PlugZap,Droplets];
function ServiceCards({services}){return <div className="service-grid">{services.map((s,i)=>{const Icon=icons[i%icons.length];return <Link className="service-card" to={'/book/'+s.id} key={s.id}><div className={'service-art color-'+i%4}><Icon size={47} strokeWidth={1.5}/><span>{groups[s.groupCode]}</span></div><div className="service-copy"><h3>{s.name}</h3><p>{s.description}</p><div className="service-price"><div><small>Tiền công tham khảo</small><strong>{money(s.laborFee)}</strong></div><span className="circle-arrow"><ArrowRight size={18}/></span></div></div></Link>;})}</div>;}
export function Dashboard(){const {user}=useApp();if(user.role==='KH')return <CustomerHome/>;if(user.role==='KTV')return <TechnicianHome/>;return <StaffHome/>;}
function CustomerHome(){const {user}=useApp(),services=useData('/services'),orders=useData('/orders?pageSize=5');return <>
<section className="customer-hero">
<div>
<span className="eyebrow">CHĂM SÓC NHÀ CỬA, THẬT DỄ DÀNG</span>
<h1>Nhà cần sửa?<br/><em>Đã có HomeFix.</em></h1>
<p>Chào {user.fullName.split(' ').at(-1)}, đặt dịch vụ ngay để thiết bị trong nhà luôn hoạt động tốt.</p>
<Link to="/services" className="btn primary">Đặt dịch vụ ngay <ArrowRight size={18}/></Link>
<div className="hero-trust"><span><ShieldCheck/> Giá rõ ràng</span><span><Clock/> Đặt lịch thuận tiện</span></div>
</div>
<div className="hero-visual" aria-hidden="true">
<div className="hero-circle"><WashingMachine size={118} strokeWidth={1}/><span className="orbit one"><Snowflake/></span><span className="orbit two"><PlugZap/></span><span className="orbit three"><Droplets/></span></div>
<div className="hero-label"><ShieldCheck size={22}/><div><b>An tâm từng dịch vụ</b><small>Xác nhận trước khi sửa chữa</small></div></div>
</div>
</section>
<div className="section-head"><div><span className="eyebrow">GIẢI PHÁP CHO NGÔI NHÀ</span><h2>Dịch vụ phổ biến</h2></div><Link to="/services" className="text-link">Xem tất cả <ArrowRight size={16}/></Link></div>
<ErrorBox error={services.error}/>
{services.loading?<Loading/>:services.data&&<ServiceCards services={services.data.filter(s=>s.isPopular).slice(0,6)}/>}
<div className="section-head"><h2>Đơn dịch vụ gần đây</h2><Link className="text-link" to="/orders">Xem lịch sử <ArrowRight size={16}/></Link></div>
<ErrorBox error={orders.error}/>
{orders.data?.length?<div className="order-list">{orders.data.slice(0,3).map(o=><OrderCard order={o} key={o.id}/>)}</div>:<Empty title="Ngôi nhà đang được chăm sóc tốt" text="Khi cần sửa chữa hoặc bảo trì, bạn có thể đặt dịch vụ trong vài bước."/>}
<div className="benefit-row"><div><ShieldCheck/><h3>Báo giá minh bạch</h3><p>Xem và duyệt chi phí trước khi thợ thực hiện.</p></div><div><CalendarDays/><h3>Chủ động thời gian</h3><p>Đặt ngay hoặc chọn lịch hẹn phù hợp.</p></div><div><Star/><h3>Lắng nghe phản hồi</h3><p>Đánh giá và gửi yêu cầu hỗ trợ sau dịch vụ.</p></div></div>
</>;}
function TechnicianHome(){const me=useData('/technicians/me',10000),orders=useData('/orders?pageSize=20',10000),action=useAction();const active=orders.data?.filter(o=>!['HoanThanh','Huy'].includes(o.status))||[];return <><PageHead eyebrow="HOMEFIX PARTNER" title="Sẵn sàng cho một ngày làm việc?" text="Theo dõi ca làm, phản hồi lệnh và cập nhật tiến độ tại đây."/><ErrorBox error={me.error||orders.error||action.error}/>{me.data&&<><div className="availability-card"><div><span className="eyebrow">TRẠNG THÁI LÀM VIỆC</span><h2><span className={'status-dot '+(me.data.availability==='SanSang'?'on':'')}/>{labels[me.data.availability]}</h2><p>{groups[me.data.skillGroup]} · {me.data.serviceArea}</p></div><button className={'btn '+(me.data.availability==='SanSang'?'':'primary')} disabled={action.busy||!!me.data.activeAssignmentSummary} onClick={()=>action.run(async()=>{await api('/technicians/me/availability',{method:'PATCH',body:{availability:me.data.availability==='SanSang'?'TamBan':'SanSang',expectedVersion:me.data.version}});me.reload();})}>{me.data.availability==='SanSang'?'Tạm nghỉ':'Bật sẵn sàng'}</button></div><div className="stat-grid three"><Stat label="Số dư ví" value={money(me.data.balance)} icon={Wallet}/><Stat label="Công việc đang giữ" value={active.length} icon={Clock}/><Stat label="Đánh giá trung bình" value={me.data.averageRating?Number(me.data.averageRating).toFixed(1)+'/5':'Chưa có'} icon={Star}/></div>{Number(me.data.balance)<Number(me.data.walletEligibility.minimum)&&<div className="notice warning">Ví cần tối thiểu {money(me.data.walletEligibility.minimum)} để nhận việc. <Link to="/wallet">Gửi yêu cầu nạp ví</Link></div>}</>}<div className="section-head"><h2>Công việc cần xử lý</h2><button className="text-btn" onClick={()=>{me.reload();orders.reload();}}><RefreshCw size={16}/> Cập nhật</button></div>{orders.loading?<Loading/>:active.length?<div className="order-list">{active.map(o=><OrderCard order={o} key={o.id}/>)}</div>:<Empty title="Chưa có ca đang chờ" text="Bật sẵn sàng để điều phối viên có thể giao công việc phù hợp."/>}</>;}
export function Stat({label,value,icon:Icon=Clock,detail}){return <div className="stat-card"><div className="stat-label">{label}<Icon size={19}/></div><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
function StaffHome(){const {user}=useApp();const summary=useData('/reports/summary',15000),orders=useData(['DPV','CSKH'].includes(user.role)?'/orders?pageSize=8':null),users=useData(user.role==='ADMIN'?'/users':null);const targets={DPV:['/orders','Mở bàn điều phối'],CSKH:['/support','Xử lý yêu cầu hỗ trợ'],KT:['/finance','Mở đối soát & ví'],ADMIN:['/admin/users','Quản lý tài khoản'],GD:['/reports','Xem báo cáo chi tiết']};return <><PageHead eyebrow="TỔNG QUAN HOẠT ĐỘNG" title={`Xin chào, ${user.fullName.split(' ').at(-1)}`} text="Dữ liệu cập nhật từ các đơn dịch vụ trong hệ thống."><Link className="btn primary" to={targets[user.role][0]}>{targets[user.role][1]} <ArrowRight size={17}/></Link></PageHead><ErrorBox error={summary.error}/>{summary.data&&<div className="stat-grid"><Stat label="Tổng đơn dịch vụ" value={summary.data.totalOrders}/><Stat label="Đã hoàn thành" value={summary.data.completedOrders} icon={ShieldCheck}/><Stat label="Giá trị đơn đã thu" value={money(summary.data.gmv)} icon={Wallet}/><Stat label="Hoa hồng đã đối soát" value={money(summary.data.commissionRevenue)} icon={Star}/></div>}<div className="two-column"><Card title={user.role==='ADMIN'?'Tài khoản hệ thống':'Đơn dịch vụ gần đây'}>{user.role==='ADMIN'?<><p>Quản lý tài khoản và quyền truy cập theo bảy vai trò nghiệp vụ.</p><strong className="big-number">{users.data?.length??'—'}</strong><p>Tài khoản đang được quản lý</p><Link to="/admin/users" className="btn">Xem danh sách <ArrowRight size={16}/></Link></>:orders.data?.length?orders.data.slice(0,4).map(o=><OrderCard key={o.id} order={o}/>):<Empty title="Mọi thứ sẵn sàng" text="Dữ liệu mới xuất hiện khi khách đặt và hoàn tất dịch vụ."/>}</Card><Card title="Luồng phục vụ khách hàng"><ol className="workflow-list">{['Tiếp nhận yêu cầu & báo giá','Khách duyệt và điều phối thợ','Sửa chữa & duyệt vật tư','Nghiệm thu, thu COD & đánh giá'].map((s,i)=><li key={s}><span>{i+1}</span><div><b>{s}</b><small>{['Kiểm tra thông tin và ảnh lỗi','Đúng chuyên môn, đúng quyền','Mọi phát sinh đều được xác nhận','Đối soát hoa hồng đúng một lần'][i]}</small></div></li>)}</ol></Card></div></>;}
export function Services(){const s=useData('/services');const [group,setGroup]=useState('all'),[search,setSearch]=useState('');
return <><PageHead eyebrow="DỊCH VỤ TẠI NHÀ" title="Bạn cần HomeFix hỗ trợ gì?" text="Chọn dịch vụ phù hợp. Báo giá chính thức sẽ được gửi để bạn xác nhận trước khi phân công thợ."/>
<div className="filter-bar" style={{marginBottom: '1rem'}}>
  <Field label="">
    <input type="text" placeholder="Tìm kiếm dịch vụ (ví dụ: Sửa máy lạnh...)" value={search} onChange={e=>setSearch(e.target.value)} style={{minWidth: '300px'}}/>
  </Field>
</div>
<div className="tabs"><button className={group==='all'?'active':''} onClick={()=>setGroup('all')}>Tất cả dịch vụ</button>{Object.entries(groups).map(([key,name])=><button key={key} className={group===key?'active':''} onClick={()=>setGroup(key)}>{name}</button>)}</div><ErrorBox error={s.error}/>{s.loading?<Loading/>:<ServiceCards services={(s.data||[]).filter(x=>(group==='all'||x.groupCode===group)&&x.name.toLowerCase().includes(search.toLowerCase()))}/>}</>;}
export function Booking(){const {serviceId}=useParams(),{user}=useApp(),navigate=useNavigate();const services=useData('/services'),policy=useData('/app-config'),a=useAction();const [form,setForm]=useState({address:user.defaultAddress||'',description:'',scheduledAt:''}),[files,setFiles]=useState([]);const uploaded=useRef(new Map()),intent=useRef(null);const service=services.data?.find(s=>s.id===Number(serviceId));const set=(k,v)=>setForm(s=>({...s,[k]:v}));
 async function submit(e){e.preventDefault();await a.run(async()=>{const ids=[];for(const file of files){if(!uploaded.current.has(file))uploaded.current.set(file,(await upload(file,'OrderFault')).id);ids.push(uploaded.current.get(file));}const body={serviceId:Number(serviceId),address:form.address,description:form.description,scheduledAt:form.scheduledAt?new Date(form.scheduledAt).toISOString():null,attachmentIds:ids};const sig=JSON.stringify(body);if(intent.current?.sig!==sig)intent.current={sig,key:uuid()};const r=await api('/orders',{method:'POST',body,key:intent.current.key});navigate('/orders/'+r.data.id);},'Đặt dịch vụ thành công.');}
 return <><PageHead eyebrow="ĐẶT DỊCH VỤ" title={service?.name||'Thông tin yêu cầu'} text="Một đơn phục vụ một thiết bị. Bạn chỉ thanh toán sau khi nghiệm thu."/><ErrorBox error={services.error}/>{services.loading?<Loading/>:!service?<Empty title="Dịch vụ không còn được cung cấp"/>:<form onSubmit={submit} className="two-column booking-layout"><Card title="Thông tin đặt lịch"><div className="contact-summary"><span className="avatar">{user.fullName.slice(0,1)}</span><div><b>{user.fullName}</b><small>{user.phone}</small><Link to="/profile">Chỉnh sửa thông tin liên hệ</Link></div></div><Field label="Địa chỉ thực hiện" hint="Ghi rõ số nhà, đường, phường và TP.HCM để điều phối đúng khu vực."><textarea required minLength={10} maxLength={500} value={form.address} onChange={e=>set('address',e.target.value)} placeholder="Ví dụ: 1 Võ Văn Ngân, Thủ Đức, TP.HCM"/></Field><Field label="Thiết bị gặp vấn đề gì?"><textarea required minLength={5} maxLength={2000} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Mô tả hiện tượng, loại thiết bị và thông tin cần lưu ý…" rows={4}/></Field><Field label="Lịch hẹn (để trống nếu cần sớm nhất)" hint="08:00–17:30, khung 30 phút; đặt trước ít nhất 30 phút, tối đa 30 ngày."><input type="datetime-local" step="1800" value={form.scheduledAt} onChange={e=>set('scheduledAt',e.target.value)}/></Field><Field label="Ảnh tình trạng thiết bị" hint="Tối đa 5 ảnh JPG/PNG, mỗi ảnh không quá 5 MB."><input type="file" accept="image/jpeg,image/png" multiple onChange={e=>{const chosen=[...e.target.files];if(chosen.length>5||chosen.some(f=>f.size>5242880)){a.setError(new Error('Chọn tối đa 5 ảnh, mỗi ảnh không quá 5 MB.'));e.target.value='';return;}setFiles(chosen);a.setError(null);}}/></Field>{files.length>0&&<small>Đã chọn {files.length} ảnh.</small>}<ErrorBox error={a.error}/><div className="form-actions"><Link className="btn" to="/services">Quay lại</Link><Submit busy={a.busy}>Gửi yêu cầu đặt dịch vụ</Submit></div></Card><aside><Card title="Chi phí tham khảo"><div className="money-lines"><div><span>Phí kiểm tra</span><b>{money(service.inspectionFee)}</b></div><div><span>Tiền công</span><b>{money(service.laborFee)}</b></div></div><div className="notice info"><ShieldCheck size={20}/><p>Điều phối viên gửi báo giá để bạn duyệt. Vật tư phát sinh chỉ được tính khi bạn đồng ý.</p></div><p className="policy-note">Miễn phí hủy trước khi thợ xuất phát. Hủy lúc thợ đang di chuyển: {policy.data?money(policy.data.cancellationFee):"đang tải mức phí"}. Khi thợ đã đến nơi, liên hệ hỗ trợ để xử lý.</p><ul className="check-list"><li><Check/>Theo dõi tiến độ trong ứng dụng</li><li><Check/>Xác nhận nghiệm thu bằng tài khoản</li><li><Check/>Thanh toán tiền mặt cho thợ</li></ul></Card></aside></form>}</>;}
export function Orders(){const {user}=useApp();const [status,setStatus]=useState(''),[page,setPage]=useState(1);const r=useData('/orders?pageSize=20&page='+page+(status?'&status='+status:''),10000);return <><PageHead eyebrow={user.role==='KH'?'DỊCH VỤ CỦA BẠN':'QUẢN LÝ CÔNG VIỆC'} title={user.role==='KH'?'Đơn dịch vụ của tôi':'Danh sách đơn dịch vụ'} text="Mở một đơn để xem thông tin và thực hiện bước tiếp theo.">{user.role==='KH'&&<Link className="btn primary" to="/services"><Plus size={18}/> Đặt dịch vụ</Link>}<button className="btn" onClick={r.reload}><RefreshCw size={16}/> Cập nhật</button></PageHead><div className="filter-bar"><Field label="Trạng thái"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tất cả trạng thái</option>{Object.entries(labels).slice(0,11).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><span>Trang {page}</span></div><ErrorBox error={r.error}/>{r.loading?<Loading/>:r.data?.length?<div className="order-list">{r.data.map(o=><OrderCard key={o.id} order={o}/>)}</div>:<Empty title="Chưa có đơn phù hợp" text="Thử chọn trạng thái khác hoặc đặt dịch vụ mới."/>}<div className="pagination"><button className="btn" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Trang trước</button><button className="btn" disabled={!r.data||r.data.length<20} onClick={()=>setPage(p=>p+1)}>Trang sau</button></div></>;}
export function Profile(){const {user,setUser,logout}=useApp(),r=useData('/users/me'),a=useAction();const [form,setForm]=useState(null),[contactPassword,setContactPassword]=useState('');useEffect(()=>{if(r.data)setForm({fullName:r.data.fullName,email:r.data.email||'',defaultAddress:r.data.defaultAddress||''});},[r.data]);return <><PageHead eyebrow="TÀI KHOẢN HOMEFIX" title="Thông tin cá nhân" text="Giữ thông tin liên hệ chính xác để việc phục vụ được thuận tiện."/><ErrorBox error={r.error||a.error}/>{form&&<div className="two-column"><Card title="Hồ sơ của bạn"><form onSubmit={e=>{e.preventDefault();a.run(async()=>{const result=await api('/users/me',{method:'PATCH',body:{...form,email:form.email||null,...(form.email!==(r.data.email||'')?{currentPassword:contactPassword}:{}),expectedVersion:r.data.version}});setUser(result.data);setContactPassword('');r.reload();});}}><div className="profile-heading"><span className="avatar large">{user.fullName.slice(0,1)}</span><div><h3>{user.fullName}</h3><span className="badge green">{roleNames[user.role]}</span></div></div><Field label="Họ và tên"><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></Field><Field label="Số điện thoại đăng nhập"><input readOnly value={user.phone}/></Field><Field label="Email"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field>{form.email!==(r.data.email||'')&&<Field label="Mật khẩu hiện tại để thay đổi email"><input required type="password" autoComplete="current-password" value={contactPassword} onChange={e=>setContactPassword(e.target.value)}/></Field>}<Field label="Địa chỉ mặc định"><textarea value={form.defaultAddress} onChange={e=>setForm({...form,defaultAddress:e.target.value})}/></Field><Submit busy={a.busy}>Lưu thông tin</Submit></form></Card><div><Card title="Đổi mật khẩu"><PasswordChange user={r.data||user} logout={logout}/></Card>{user.role==='KH'&&<Card title="Trở thành kỹ thuật viên"><p>Bạn có kinh nghiệm sửa chữa? Gửi hồ sơ chuyên môn để quản trị viên xét duyệt.</p><Link to="/applications" className="btn">Đăng ký cộng tác</Link></Card>}<button className="btn danger full" onClick={logout}>Đăng xuất tài khoản</button></div></div>}</>;}
export function Notifications(){const r=useData('/notifications',15000),a=useAction();return <><PageHead eyebrow="CẬP NHẬT MỚI" title="Thông báo" text="Các thay đổi liên quan đến đơn dịch vụ và tài khoản của bạn."/><ErrorBox error={r.error||a.error}/>{r.loading?<Loading/>:r.data?.length?<div className="notifications-list">{r.data.map(n=><article className={'notification '+(!n.readAt?'unread':'')} key={n.id}><div className="notification-icon"><Bell size={20}/></div><div><h3>{n.title}</h3><p>{n.body}</p><small>{date(n.createdAt)}</small><div className="actions">{n.orderId&&<Link to={'/orders/'+n.orderId} className="text-link">Xem đơn dịch vụ <ArrowRight size={14}/></Link>}{!n.readAt&&<button className="text-btn" disabled={a.busy} onClick={()=>a.run(async()=>{await api('/notifications/'+n.id+'/read',{method:'PATCH',body:{}});r.reload();},'')}>Đánh dấu đã đọc</button>}</div></div></article>)}</div>:<Empty title="Chưa có thông báo mới"/>}</>;}
